### ISSUE TITLE
First-person view

### ISSUE THREAD

**Issue by pgmann** [pgmann/SpectatorPlus#26]
Add a first-person view to SpectatorPlus - so that the view is locked onto the player being spectated when they are punched, until the spectator presses CROUCH, which releases them back into normal spectating mode.

Enable first-person mode: Punch a player Disable first-person mode: Press CROUCH

_Optional: There should be a book added to the spectator's inventory to allow them to view the player's stats (e.g. health) and their inventory and armour._

**Comment by Noket** [comment]
I've been developing a plugin that does just this. I don't mind sharing the source, so long as you give credit. The plugin allows multiple people to spectate a person in first person .. all you have to do is create an instance of a runnable in a method I defined, and declare the update frequency. It tracks and syncs yaw,pitch,x,y,z,inventoryopen,etc ..
