### ISSUE TITLE
[Idea] Spectate radius command

### ISSUE THREAD

**Issue by TNSPredator** [pgmann/SpectatorPlus#36]
So here is the idea, short and sweet: 
- Allow users with the following permission node:  <spectate.radius>  to issue this command /spec radius <X>
        - This displays all players with in the radius of X blocks and displays them in the GUI. 

- Another feature that you could implement is permission nodes for certain radius's. For example <spectate.radius.30> would only allow <X> to  be 30 in /spec radius <X>. 

**Edit** by pgmann:
* */spec mode radius* command;
* config option *spectateradius: 30* or something like that.

**Comment by pgmann** [comment]
I have decided not to add this feature for the foreseeable future, as I don't think there's a big demand for it and it has limited uses.
Closing as won't fix.
