### ISSUE TITLE
Add a "spectate.hide" permission back

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [pgmann/SpectatorPlus#43]
It would be useful with a permission that people could have which prevent other players from spectating them, without the need of toggling it manually :)

**Comment by AmauryCarrade** [comment]
I agree with that.

**Comment by pgmann** [comment]
Problem: it's really hard to stop op's from automatically inheriting the 'spectate.hide' permission, which does away with the install and play possibility if everyone is given all permissions ('*').

**Comment by TheOnlyRealTGS** [comment]
Yup, that's an issue with every plugin out there doing similar things, which is why permission plugins usually [warn](https://github.com/PEXPlugins/PermissionsEx/wiki/Basic-Permissions-Setup#kitchen-sink-notes) about this. It's super simple to solve by giving ops a negated permission like _-spectate.hide_ and I don't think we shouldn't implement this because the average server owner is stupid.

**Comment by pgmann** [comment]
Fair point. I'll see about it :)

**Comment by TheOnlyRealTGS** [comment]
:+1:

**Comment by pgmann** [comment]
Should I add a message that says "Hide mode is enabled" when players with this permission join? Or should it remain silent?

**Comment by TheOnlyRealTGS** [comment]
Just let it remain silent imo :)
