### ISSUE TITLE
Allow /spec off by default idea/bug

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [pgmann/SpectatorPlus#44]
So I have a problem:
I added the spectate.use permission for my worlds where I have arenas, but if people join the actual games they have permission to spectate while in game, and that messes stuff up :(
So there's a couple of ways to solve this:
Allow /spec off by default
Add a permission for /spec off and /spec on instead of 1 for both

**Comment by AmauryCarrade** [comment]
> Add a permission for `/spec off` and `/spec on` instead of 1 for both

Good idea. But op by default.

> Allow `/spec off` by default

I don't think this is a good idea.

**Comment by TheOnlyRealTGS** [comment]
Glad you like it, even better idea: Don't remove the _use_ permission but keep it to prevent that people's permissions break. So just add 2 new ones :)

**Comment by AmauryCarrade** [comment]
Two new permissions: spectate.use.on and spectate.use.off; spectate.use implies .on and .off .

**Comment by TheOnlyRealTGS** [comment]
Okay nice! Just make sure that .on and .off doesn't inherit .use :)

**Comment by TheOnlyRealTGS** [comment]
Hi, just a quick question, do you have an approximate ETA for this? :)
(Sorry for asking)

**Comment by pgmann** [comment]
When we have some time to work on it we will. GitHub issues are usually the
first thing we fix/add. Personally, I've been very busy with school, exams
and sickness...

**Comment by TheOnlyRealTGS** [comment]
Okay no worries!

**Comment by pgmann** [comment]
Next issue in line to get resolved. I'll prioritise this next time I have free time, maybe tomorrow.

**Comment by TheOnlyRealTGS** [comment]
Awesome!

**Comment by TheOnlyRealTGS** [comment]
Thank you.
