### ISSUE TITLE
Not compatible with plugin managers

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [pgmann/SpectatorPlus#47]
If you load/unload the plugin while the server is running the plugin doesnt load.
http://pastebin.com/5bBwAdat

**Comment by pgmann** [comment]
May I suggest trying pm-pluginmanager off BukkitDev instead, just to test? I want to make sure it's not just a bug with PlugMan.

And could you test with the S2.0 version of the plugin as well to see if it works ok with it?

Thanks.

**Comment by TheOnlyRealTGS** [comment]
That project is currently not being maintained by its manager in a consistent manner - quote from author :/

**Comment by pgmann** [comment]
Sorry, where's it say that? I suppose it's true though... I'm very busy with exams and don't get much time to code...

**Comment by TheOnlyRealTGS** [comment]
On http://dev.bukkit.org/bukkit-plugins/pm-pluginmanager/

**Comment by pgmann** [comment]
Oh sorry, I thought you meant this plugin was inactive :D

Well, pm-pluginmanager works for me, though it has a few bugs like crashing your server if you unload a plugin with a dependency... It's been a while since I tested if it worked with SpectatorPlus.

Did you try testing PlugMan with S2.0? Did it work?

**Comment by TheOnlyRealTGS** [comment]
No, will do

**Comment by TheOnlyRealTGS** [comment]
Actually, I'm already using PlugMan v2.0.3 :)

**Comment by pgmann** [comment]
I meant PlugMan with SpectatorPlus version S2.0.

**Comment by TheOnlyRealTGS** [comment]
Ah instead of 2.1?

**Comment by pgmann** [comment]
Please.

**Comment by TheOnlyRealTGS** [comment]
I created a new server and tested with 2.0 no errors, tested with 2.1 no errors. I think you need to have arenas in order for the bug to happen?

**Comment by pgmann** [comment]
Maybe. Give it try with arena mode, see if you can nail it down. It'd help
me a lot to have something specific :)

**Comment by TheOnlyRealTGS** [comment]
I got an error on loading that http://pastebin.com/G2DPQBR9

**Comment by pgmann** [comment]
Make sure you regenerated the config file when you downgraded. That might
be the cause.

**Comment by TheOnlyRealTGS** [comment]
I deleted the toggles.yml and got this error http://pastebin.com/v8hNYvms

**Comment by pgmann** [comment]
Delete the entire SpectatorPlus data folder. The arenas are stored in a
different way if I remember correctly.

**Comment by TheOnlyRealTGS** [comment]
They are stored in the setup.yml file

**Comment by pgmann** [comment]
Yes, they are. So make sure you've deleted it

**Comment by TheOnlyRealTGS** [comment]
But whats the point of testing it, when the setup isn't the same as on my production server?

**Comment by pgmann** [comment]
Well, mainly to see where the code broke to help us fix it. Please, try with a fresh data folder to see if it works when you reload.

**Comment by TheOnlyRealTGS** [comment]
But that's what I did 2 days ago
https://github.com/pgmann/SpectatorPlus/issues/47#issuecomment-83650969

**Comment by pgmann** [comment]
Yes, but did you enable arena mode and test that?

**Comment by TheOnlyRealTGS** [comment]
How do I do that on 2.0?

**Comment by pgmann** [comment]
It should be exactly the same as 2.1. Just use /spec mode arena, then /spec
arena add <name>.

**Comment by TheOnlyRealTGS** [comment]
It seems to work on 2.1

**Comment by pgmann** [comment]
So can this be closed then if this works? I think it's something to do with your own personal setup, possibly world names.

**Comment by TheOnlyRealTGS** [comment]
I doubt it, some plugins works, others don't with plugman

**Comment by TheOnlyRealTGS** [comment]
Think this was fixed by #49
