### ISSUE TITLE
Error on shutdown

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [pgmann/SpectatorPlus#48]
Saw this: http://pastebin.com/LtpUdpdN
Theres also this on start: http://pastebin.com/3rtSd5kN

**Comment by pgmann** [comment]
There's definitely something wrong with your config. Can you post setup.yml and toggles.yml here please?

**Comment by TheOnlyRealTGS** [comment]
http://pastebin.com/DirYDyNR
http://pastebin.com/HecYNqU5

**Comment by TheOnlyRealTGS** [comment]
It seems like the whole plugin is broken, not 100% sure yet though

**Comment by pgmann** [comment]
Hmm... `world: Lobby2.0`... Try renaming your world so it doesn't have a dot.

And just to confirm, would the plugin work if you re-created all those arenas? (i.e. if you deleted the plugin data folder SpectatorPlus)

**Comment by TheOnlyRealTGS** [comment]
Sorry but I can't do that. My lobby world is referenced by tons of plugins. And I don't have time to recreate all the arenas, this started being a problem recently though, so maybe a compatibility problem with spigot?

**Comment by TheOnlyRealTGS** [comment]
Probably related to #49
