### ISSUE TITLE
Plugin not working 

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [pgmann/SpectatorPlus#49]
I'm on #121
Getting this error on startup:
http://pastebin.com/7R8iPgrY

setup: http://pastebin.com/5DVbX4UR

**Comment by TheOnlyRealTGS** [comment]
I think I fixed this by deleting my spectators.yml.

**Comment by pgmann** [comment]
Glad to hear. I thought it was something to do with your config ;)

**Comment by TheOnlyRealTGS** [comment]
Yeah, I don't understand why there was any people it in though

**Comment by pgmann** [comment]
If they log out in spectator mode they will be in that file.

**Comment by TheOnlyRealTGS** [comment]
Yeah I get that, but wouldn't it make sense to clear it at server restart or?

**Comment by pgmann** [comment]
No, it stays there permanently - in case, during a UHC game for example,
they restart the server between episodes or something.

**Comment by TheOnlyRealTGS** [comment]
Okay, I guess that makes sense.
