### ISSUE TITLE
[Idea] New toggle to auto-enable no-clip mode (gamemode 3)

### ISSUE THREAD

**Issue by pgmann** [pgmann/SpectatorPlus#52]
See here: https://github.com/AmauryCarrade/UHPlugin/issues/108

There should be a toggle in toggles.yml to **auto-enable no-clip mode** for spectators and **stop them from leaving it** with the inventory button or the command (/spec b)

**Comment by ElDude1** [comment]
Great! Can't wait for this to be added. Any idea when you'll get to it? Thank you alot! :+1:

**Comment by pgmann** [comment]
Possibly tomorrow (Saturday). If not, definitely next week. Exams over, off
for summer!

**Comment by pgmann** [comment]
Got it done. Enjoy!

**Comment by ElDude1** [comment]
Thank you so much! one last, dumb question. How do I download the new version?

**Comment by pgmann** [comment]
Ah yes. http://ci.pgmann.cf/

**Comment by pgmann** [comment]
Relevant toggle in toggles.yml: `spectators.useVanillaSpectate` (`/spec config spectators.useVanillaSpectate true`)

**Comment by ElDude1** [comment]
Thanks alot, the no clip mode works like a charm. Is the spectators.useVanillaMode true supposed to force gamemode 3? Because I still get put into the normal spectator mode, but I can select the no-clip from the inventory. Sorry if I am bothering you with this.

**Comment by pgmann** [comment]
It should force enable no-clip mode... It worked for me...

**Comment by ElDude1** [comment]
Sorry, for some reason the "true" was inside of singlequotes. Works fine now, thanks you!
