### ISSUE TITLE
[Conflict] You can see background mobs, players and so on from AntiAura (Hack blocker)

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [pgmann/SpectatorPlus#53]
So you can see the methods [this](http://www.spigotmc.org/resources/antiaura-hack-blocker-v5-0.1368/) plugin uses to combat hacks. Long story short, it spawns invisible squids to detect forcefield/aura etc, and spawns invisible players to combat tracers/maphacks.
This only happens when you enter no-clip mode.
Maybe there's a way around this? 
I wrote to the author too, probably best solved from his end: http://www.spigotmc.org/threads/antiaura-hack-blocker-v5-0-paid.31675/page-138#post-800692

**Comment by pgmann** [comment]
Keep me updated on this. Being a premium resource I can't really do anything about this...
I never saw that anti-cheat plugin before, it sounds pretty creative ;)

**Comment by TheOnlyRealTGS** [comment]
Yeah, it seems to be the most effective one, eventually you can mail me for a version so you can test :)

**Comment by pgmann** [comment]
Okay, but I think it might be easier for the author of AntiAura to do the
fix using the API.

>

**Comment by TheOnlyRealTGS** [comment]
Yep, I think that is the easiest solution too.

**Comment by TheOnlyRealTGS** [comment]
Hmm, it doesn't seem to happen every time (maybe because I updated AA?).

**Comment by pgmann** [comment]
Has this been fixed yet?

**Comment by AmauryCarrade** [comment]
Untested by me.

**Comment by TheOnlyRealTGS** [comment]
I don't know, the plugin wont load https://github.com/pgmann/SpectatorPlus/issues/50

**Comment by AmauryCarrade** [comment]
You cannot hide an invisible entity from the players in vanilla spectator mode (3), so this cannot be solved on our side.
