### ISSUE TITLE
Cannot use the API: “SpectatorPlus cannot be resolved to a type”

### ISSUE THREAD

**Issue by terrainwax** [pgmann/SpectatorPlus#54]
SpectatorPlus cannot be resolved to a type
when i want to use the api on my plugin

**Comment by AmauryCarrade** [comment]
Setup? Dependency/repo used? Code? Useful title?

Can't help without that.

**Comment by terrainwax** [comment]
Its when i want to setup the api

**Comment by terrainwax** [comment]
i have use the api setup of the bukkit page

**Comment by AmauryCarrade** [comment]
> Dependency/repo used?

I can help you, but it's hard with these answers.

**Comment by terrainwax** [comment]
I dont understand want you want :s i m french 
I dont understand this "Dependency/repo used?"

**Comment by AmauryCarrade** [comment]
Je suis français :) .

Cela correspond à la dépendance que vous avez importé, quel JAR (si il a été directement ajouté à votre IDE (Éclipse, IntelliJ...), ou au dépôt (“repo”) Maven utilisé, si vous utilisez Maven.

En bref, comment vous avez intégré SPlus dans votre projet.

**Comment by pgmann** [comment]
If you're using the latest development version, you can do `SpectatorPlus.
getAPI()`. This returns the SpectateAPI instance. It only works in the B2.1
development builds though.

**Comment by pgmann** [comment]
If you're using the latest development version, you can do `SpectatorPlus.
getAPI()`. This returns the SpectateAPI instance. It only works in the B2.1
development builds though.

**Comment by terrainwax** [comment]
Je l ai ajouter en import sur eclipse j ai clique droit sur mon projet properties javabuildpath et je l es ajouter a la librarie

**Comment by AmauryCarrade** [comment]
> Cela correspond à la dépendance que vous avez importé, **quel JAR** (si il a été directement ajouté à votre IDE (Éclipse, IntelliJ...) [...].

**Comment by terrainwax** [comment]
c'est cette version que j ai ajouter SpectatorPlus-S1.9.2  car je fait un plugin  pour bukkit 1.7.10

**Comment by terrainwax** [comment]
if i use the last dev version where i place this SpectatorPlus.getAPI()? and its this SpectatorPlus.getAPI() or this SpectateAPI.getAPI();

**Comment by AmauryCarrade** [comment]
With the latest version from the build server, you check if SpectatorPlus is available (through a `depend` entry in the `plugin.yml`, or a `soft-depends` and a check with code); then you use anywhere:
```java
SpectatorPlus.getAPI()
```
to get the instance of the SpectateAPI class to use.

**Comment by AmauryCarrade** [comment]
But this version is a 1.8 version. This said, CraftBukkit / Spigot 1.8+ work just fine.

**Comment by AmauryCarrade** [comment]
Problem solved?

**Comment by pgmann** [comment]
Assuming this is solved. Closed.
