### ISSUE TITLE
How can I build this without using Maven?

### ISSUE THREAD

**Issue by MrBeefchop** [pgmann/SpectatorPlus#58]
Which JAR Files (by Java Build Path - Libraries) do you use?

Because Maven thing doesnt work by me.

Please add Messages.yml and that you can edit the Prefix!

**Comment by MrBeefchop** [comment]
And I got one error when I use the SpectatorPlus.2.0.jar
Server: Spigot 1.8.6 - LASTET

Error: http://pastebin.com/d2h90UM7

**Comment by MrBeefchop** [comment]
I can't use 1.8.1 because of other plugins

**Comment by AmauryCarrade** [comment]
We only use Maven to compile, and the dependencies are [in the `pom.xml` file](https://github.com/pgmann/SpectatorPlus/blob/rewrite/SpectatorPlus/pom.xml#L94): for the last development version (branch `rewrite`), Bukkit API 1.8.3, zLib 0.99 (shaded, good luck to do that without Maven), and Apache Commons Lang 3.3.2.

The possibility to change the texts is already planned: see #32.

The error you mentioned will not be fixed because it's already fixed in the last development version (because the way arenas are stored was rewrote). This said, this version is only compatible with Bukkit 1.8.3+.

By the way, any plugin working with Bukkit 1.8.0 should work with 1.8.3 (except if NMS are used).

----
Please open **one issue per problem or suggestion**. Thanks.

**Comment by MrBeefchop** [comment]
Spigot 1.8.3 ? Works too? I hope

**Comment by AmauryCarrade** [comment]
It works with both CraftBukkit and Spigot.
If a plugin works with CraftBukkit, it **always** works with Spigot (same version), except maybe in some *very rare* cases.

**Comment by MrBeefchop** [comment]
Now I get much Errors... On start..
And I just renamed the jar 
http://pastebin.com/vJhS8kew

But in the Programming programm no Errors only a ! By the File..
I use eclipse

**Comment by MrBeefchop** [comment]
And please add messages.yml by the next update. It would be very helpful!

Messages.yml = Please the Prefix too ! c:

**Comment by AmauryCarrade** [comment]
Your dependencies are badly managed. Don't know how you compiled the plugin, but you dit it wrongly.
Learn how to use Maven if you want to compile this plugin (and many others).

**Comment by MrBeefchop** [comment]
Yes now I have convert it to Maven?? And I have done this what he said:
Maven Eclipse plugin installation step by step:

Open Eclipse IDE
Click Help -> Install New Software...
Click Add button at top right corner
At pop up: fill up Name as "M2Eclipse" and Location as "http://download.eclipse.org/technology/m2e/releases"
Now click OK

Finally,

Click on an existing project
Select Configure -> Convert to Maven Project

http://stackoverflow.com/questions/8620127/maven-in-eclipse-step-by-step-installation

When I have done this it this Errors by Export it:

http://i.imgur.com/jDDkLGC.png

**Comment by MrBeefchop** [comment]
By the source package I only edited most of the messages

**Comment by AmauryCarrade** [comment]
You probably badly configured Maven. The Maven root is in the `SpectatorPlus` subfolder (where the `pom.xml` file is).

**Comment by MrBeefchop** [comment]
SHould I create a java Projekt or a Maven Project?

**Comment by AmauryCarrade** [comment]
Sorry, I don't use Eclipse. But I suppose a Maven project is required.
You may [try to follow this tutorial](http://wiki.bukkit.org/Plugin_Tutorial), but it explains how to create an empty project. It's probably similar.

**Comment by MrBeefchop** [comment]
Should the zlib.tar.gz or should I be a .jar?

**Comment by MrBeefchop** [comment]
Because I think this creates the errors..

**Comment by MrBeefchop** [comment]
Please send me the download Link where you have download this..

**Comment by AmauryCarrade** [comment]
There isn't any download link: in the `rewrite` branch, the zLib dependency is shaded into the Jar with Maven.
There's a [JAR file](http://maven.carrade.eu/artifactory/snapshots/fr/zcraft/zlib/0.99-SNAPSHOT/) downloaded by Maven and merged with the final JAR, but Maven handle this alone.

**Comment by AmauryCarrade** [comment]
No longer active. Reopen if needed.
