### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by AmauryCarrade** [pgmann/SpectatorPlus#62]
This project don't have an automated Maven repository.
I used to manually (!) update a repository on my server, but it is pretty outdated.

Do you want to install a repository manager on your server, like Artifactory? Or to use [my Artifactory instance](http://maven.carrade.eu)? Or nothing, but without that it's hard to use the API.

**Comment by pgmann** [comment]
Good point. I'll see about it soon, may not have time tonight to finish it.

**Comment by pgmann** [comment]
(Is there an apt- source I can use so I can auto-update?)

**Comment by AmauryCarrade** [comment]
(I don't think so.)

**Comment by pgmann** [comment]
Artifactory setup complete. Have a look: https://ci.pgmann.cf/maven/

**Comment by pgmann** [comment]
What should I actually archive in artifactory? Just the `.jar` or is the `pom.xml` needed as well?

**Comment by AmauryCarrade** [comment]
You should archive the `.jar` and the associated `.pom`. There is an Artifactory plugin for Jenkins to do that :) .

**Comment by AmauryCarrade** [comment]
On the side: how did you removed the `/artifactory/` from the URL? I want my repository URL to be `maven.carrade.eu`, but it is `maven.carrade.eu/artifactory` currently :c .

**Comment by pgmann** [comment]
You rename the .war file (I installed tomcat first, then dropped
artifactory.war into /var/lib/tomcat8/webapps/). You can name it anything
(e.g. maven.war) Make sure you rename the other folder with the same name
in the webapps folder.

**Comment by pgmann** [comment]
Oh yeah, and calling it ROOT.war and ROOT (delete old ROOT folder) will
make it have no path (removes the word artifactory)

**Comment by pgmann** [comment]
The `pom.xml` is now archived in artifactory as well. I have one problem - all the builds are put in the release repository instead of the snapshot one (where they should go). Any idea how to fix that?

**Comment by AmauryCarrade** [comment]
Thanks for the URL tip!

---

My Jenkins build is configured like this:
![Jenkins build config related to Artifactory](http://raw.carrade.eu/s/1452607038.png)

With that, if the version is `something-SNAPSHOT` (e.g. `zLib 0.99-SNAPSHOT`), the build is archived in the `snapshots` repositories; else, in the `relases` one.

**Comment by AmauryCarrade** [comment]
Finally I can update my [dependencies](https://github.com/zDevelopers/UHPlugin/commit/945e881bcded625694a738271f060f274108b707) o/ 5e881bcded625694a738271f060f274108b707

**Comment by pgmann** [comment]
(you might want to wait a bit, switching branches about ;) )

**Comment by AmauryCarrade** [comment]
I updated [to use the `LATEST` version](https://github.com/zDevelopers/UHPlugin/commit/1b75db7f53c6fd0a7e4a3c270595ba2ceda48c80).

**Comment by pgmann** [comment]
Can you confirm it's working now? (Haven't got snapshot versioning working yet)

**Comment by AmauryCarrade** [comment]
It's working on my side currently. I got [a lot of warnings related to the HTTPS certificate](http://jenkins.carrade.eu/job/UltraHardcoreReloaded/264/console), but it works well.

**Comment by AmauryCarrade** [comment]
Message updated, it's **not** working.

**Comment by pgmann** [comment]
Hmm... I see you have Java 1.8 installed on your server, but your Jenkins is using 1.7... it may be using a different, old keystore that doesn't have my cert's root in it...

**Comment by pgmann** [comment]
You could try using this to debug it...

https://confluence.atlassian.com/display/KB/Unable+to+Connect+to+SSL+Services+due+to+PKIX+Path+Building+Failed

Not sure how you'd execute that command as jenkins though. Maybe in a Jenkins job pre-step?

**Comment by pgmann** [comment]
Is this still not working @AmauryCarrade? I'm using the snapshot repository now since this commit: 3b230fec1b1112bc4defbd88ded84b7e1057a6ab

**Comment by pgmann** [comment]
I think this can finally be closed, if you can confirm it working with UHPlugin please @AmauryCarrade? Note the repo path has changed - see the README file for details.

**Comment by AmauryCarrade** [comment]
Maven/Jenkins [is still complaining about invalid certificates](http://jenkins.carrade.eu/job/UltraHardcoreReloaded/304/console). This is probably the cause of #64 as the build server is still using an old cached build, if the API changed.

**Comment by pgmann** [comment]
Please try querying your Java trust store for the root certificate used to sign my cert.
```
keytool -list -keystore /etc/ssl/certs/java/cacerts | grep dst
Enter keystore password:  changeit
```
Expected output:
```
debian:dst_root_ca_x3.pem, 30-Nov-2015, trustedCertEntry,
debian:dst_aces_ca_x6.pem, 30-Nov-2015, trustedCertEntry,
```

**Comment by AmauryCarrade** [comment]
```
debian:dst_root_ca_x3.pem, 8 sept. 2014, trustedCertEntry, 
debian:dst_aces_ca_x6.pem, 8 sept. 2014, trustedCertEntry, 
```

A bit old indeed. But I manually added your certificate to the store ([following this](http://stackoverflow.com/a/32074827/5599794)), without success.

**Comment by pgmann** [comment]
Would be interested to see if a local build of UHPlugin would work...

**Comment by AmauryCarrade** [comment]
It works locally.

**Comment by pgmann** [comment]
Wow, ok... How about the VM command line?

**Comment by AmauryCarrade** [comment]
Found it. Jenkins uses it's own JRE, not the system-wide JRE 7. I linked the `cacerts` file of this JRE to `/etc/ssl/certs/java/cacerts` and [now it works](http://jenkins.carrade.eu/job/UltraHardcoreReloaded/309/console).

**Comment by pgmann** [comment]
Ah, very nice! Glad it worked in the finish up. Yay we fixed an issue!

**Comment by pgmann** [comment]
Hang on, are you sure it's using the build from my maven repo?
```
[INFO] Building UHCReloaded 1.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: https://mvn.pgmann.cf/org/bukkit/bukkit/1.8.3-R0.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://mvn.pgmann.cf/fr/zcraft/zlib/0.99-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://mvn.pgmann.cf/com/pgcraft/SpectatorPlus/maven-metadata.xml
[INFO] Downloading: https://mvn.pgmann.cf/com/comphenix/protocol/ProtocolLib-Parent/v3-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://mvn.pgmann.cf/com/comphenix/executors/BukkitExecutors/1.1-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://mvn.pgmann.cf/org/mcstats/bukkit/metrics-lite/R8-SNAPSHOT/maven-metadata.xml
```
All these URLs return 404, including the actual one for SpectatorPlus. Maybe I should be using `https://mvn.pgmann.cf/repository/maven-snapshots/...` instead? That returns [the expected file](https://mvn.pgmann.cf/repository/maven-snapshots/com/pgcraft/SpectatorPlus/maven-metadata.xml).

**Comment by AmauryCarrade** [comment]
I modified the build as mentioned in the commit above and it works locally, even when I delete the local repository or with the `-U` flag. Waiting for the Jenkins build to finish...

**Comment by AmauryCarrade** [comment]
Yep, this time [it seems to be fine](http://jenkins.carrade.eu/job/UltraHardcoreReloaded/310/console):

```log
[INFO] Downloading: https://mvn.pgmann.cf/repository/maven-snapshots/com/pgcraft/SpectatorPlus/B3.0-SNAPSHOT/SpectatorPlus-B3.0-20160503.161555-5.pom
[INFO] Downloaded: https://mvn.pgmann.cf/repository/maven-snapshots/com/pgcraft/SpectatorPlus/B3.0-SNAPSHOT/SpectatorPlus-B3.0-20160503.161555-5.pom (4 KB at 37.5 KB/sec)
[INFO] Downloading: https://mvn.pgmann.cf/repository/maven-snapshots/com/pgcraft/SpectatorPlus/B3.0-SNAPSHOT/SpectatorPlus-B3.0-20160503.161555-5.jar
[INFO] Downloaded: https://mvn.pgmann.cf/repository/maven-snapshots/com/pgcraft/SpectatorPlus/B3.0-SNAPSHOT/SpectatorPlus-B3.0-20160503.161555-5.jar
```

But you broke the `LATEST` version, I had to explicitly set it. It's not a problem this said.

**Comment by pgmann** [comment]
Great! I assume it's because Nexus doesn't support LATEST?

**Comment by AmauryCarrade** [comment]
Probably.

**Comment by AmauryCarrade** [comment]
You should update the `README`, as it suggest to use the `LATEST` version.

**Comment by pgmann** [comment]
Will do tomorrow. (On phone)

**Comment by pgmann** [comment]
I updated the `README` and also added an API Usage section. Would you please update the line of code which is commented out to show the correct, non-deprecated usage? (Last line of code snippet in the file)

**Comment by pgmann** [comment]
(@AmauryCarrade, please log in to my Jenkins and I can now give you access to build SpectatorPlus on demand - just need to make sure of the username!)

(Slightly off-topic)

**Comment by AmauryCarrade** [comment]
(Done. It's the same username as GitHub.)

**Comment by pgmann** [comment]
(There, you have read, build and workspace access to SpectatorPlus and Spigot)

**Comment by pgmann** [comment]
@AmauryCarrade: Another change (sorry!). Remove `/repository/maven-snapshots` from the URL to leave just `https://mvn.pgmann.cf/` as the repo URL. This should be the last change necessary for a while, I hope!

[Technical details: Nexus was using ~1GB of RAM after running a while. So I'm using Jenkins as a [Maven Repository Server](https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Maven+Repository+Server) now.]

**Comment by pgmann** [comment]
@AmauryCarrade ping, see above.
