### ISSUE TITLE
Don't save spectators option

### ISSUE THREAD

**Issue by YoLaw** [pgmann/SpectatorPlus#68]
Hello!
I thought a feature. In config.yml, it could be good to select if specs will be save.
For exemple, I'm runing an UHC server, and if specs are saved, then players will be spectators when they'll join next game.
Thanks! :)

**Comment by pgmann** [comment]
This would be better dealt with by UHPlugin. Image mid-game a spectator leaves for a minute, then rejoins. If I implemented your idea and you turned off spec saving they would no longer be a spectator in this game.

On the other hand, UHPlugin could add a 'force spec off in join' setting for players who aren't registered in a game, as it could save registrations until the end of the game, even if the player quits and rejoins.

(@AmauryCarrade)

**Comment by AmauryCarrade** [comment]
It's already the case. Players joining before the beginning of the game are put in non-spectating mode, and after, in the right mode for them.

13 mai 2016 10:23 "pgmann"  a écrit:
	This would be better dealt with by UHPlugin. Image mid-game a spectator leaves for a minute, then rejoins. If I implemented your idea and you turned off spec saving they would no longer be a spectator in this game.

	On the other hand, UHPlugin could add a 'force spec off in join' setting for players who aren't registered in a game, as it could save registrations until the end of the game, even if the player quits and rejoins.

	(@AmauryCarrade (https://github.com/AmauryCarrade))

**Comment by pgmann** [comment]
@YoLaw, I assume you use UHPlugin for UHC?

**Comment by YoLaw** [comment]
Before last week I used UHPlugin... But thé problem is: I have an hosted Minecraft server, ans when I launch UHC, many players have bugs due to map generation.
I foundt another plugin wich generate the map when server is launching. It works very good and my UHC is 100% debuged! But I prefered UHPlugin for it features :( 
So! I think my idea can be good for servers runing another plugin than UHPlugin! :)

**Comment by AmauryCarrade** [comment]
@YoLaw, if you want UHCr, you can use the [WorldBorder](http://dev.bukkit.org/bukkit-plugins/worldborder/) plugin alongside to pre-generate the world (using `/wb fill`).
I avoid features already available in others plugins :) .

*/offTopic*

**Comment by pgmann** [comment]
Where would a Toggle like this belong?

`onSpectatorModeChanged.saveSpectators`, or any better ideas?

**Comment by AmauryCarrade** [comment]
With an explanation comment it's fine.
