### ISSUE TITLE
Hide coordinates

### ISSUE THREAD

**Issue by YoLaw** [pgmann/SpectatorPlus#69]
Hello!
I've a good idea for your plugin. 
In effect I use this for an UHC server. So players can see others players's coordinates.
It is a problem, and it will be good if you add an option to disable coordinates in F3 menu! :)
Thanks! :)

**Comment by pgmann** [comment]
Hmm, thought this would be quite easy but actually it won't - I'm not sure if it's possible to set gamerules per player (`/gamerule reducedDebugInfo true`). Is it even possible using packets? I had a look at ProtocolLib but wasn't sure if it supported this or how...

Of course, the simple alternative would be to hide coordinates for everyone then use a command from a plugin such as Essentials, which spectators couldn't access due to command whitelisting.

**Comment by AmauryCarrade** [comment]
It is probably easy to send manually a packet (even without ProtocolLib, with a bit of reflection) to achieve that. I can try something if you want :) .

13 mai 2016 11:44 "pgmann"  a écrit:
	Hmm, thought this would be quite easy but actually it won't - I'm not sure if it's possible to set gamerules per player (/gamerule reducedDebugInfo true). Is it even possible using packets? I had a look at ProtocolLib but wasn't sure if it supported this or how...

	Of course, the simple alternative would be to hide coordinates for everyone then use a command from a plugin such as Essentials, which spectators couldn't access due to command whitelisting.

**Comment by pgmann** [comment]
Yep, that might be better than me messing about with it ;)

**Comment by AmauryCarrade** [comment]
For reference, we only need to send [this packet](http://wiki.vg/Protocol#Entity_Status) to enable or disable reduced debug infos.

**Comment by pgmann** [comment]
Ah yes! Never thought of looking there ;)

22	Enables reduced debug for the given player
23	Disables reduced debug for the given player

**Comment by YoLaw** [comment]
My friend is developper, and he achieve this easily! :)

**Comment by pgmann** [comment]
Good job!

(One side note, why `ReduceDebugInfos` when the gamerule is `ReducedDebugInfo`?)

**Comment by AmauryCarrade** [comment]
(Oh, you're right.) (I'll change that everywhere, for coherence, while I still can.)

**Comment by YoLaw** [comment]
This feature is useful, but with my friend we detected a fault: players who have a specific client with mods who displays coordinates, they can see coordinates!
It's the case of Laby Mod! :)

**Comment by pgmann** [comment]
If they're 'hacking' maybe they should be banned ;)

**Comment by YoLaw** [comment]
Yes! But it is not easy to detect... But I know that plugins can't manage clients, and hide F3 coordinates is the best solution... :/

**Comment by pgmann** [comment]
Well, we could technically fake the coordinates by adding a random number to them (maybe? might mess up chunk loading), which would make the coordinates useless.

**Comment by AmauryCarrade** [comment]
I'm [aware of this problem](https://github.com/zDevelopers/zLib/blob/master/src/main/java/fr/zcraft/zlib/tools/players/ReducedDebugInfo.java#L105-L106) but I don't see any elegant workaround (as for now).

**Comment by YoLaw** [comment]
@pgmann yes it's a good idea, but I think it could be difficult to do!

**Comment by pgmann** [comment]
Yeah...

> You must modify **ALL** packets.
> As you may know not only player have location, also items, mobs, other players, weather effects.
world and chunk packets, also block updates and a few others, like respawn and login.
> All packets must be "adapted" to follow the given player's "local space and time".

([Source](https://bukkit.org/threads/fake-coordinates.248205/#post-2354980))

**Comment by AmauryCarrade** [comment]
If this is achieved, it should be in a dedicated plugin, I think. We are out of the SpectatorPlus scope.

**Comment by YoLaw** [comment]
Hardcore! :o

**Comment by pgmann** [comment]
NoCheat++++ ;)

**Comment by pgmann** [comment]
Ooh! http://dev.bukkit.org/bukkit-plugins/randomcoords/

**Comment by YoLaw** [comment]
Ever tested, but not working, with error messages! :) No problem it's not your job to give me other plugins! :)

**Comment by pgmann** [comment]
Yeah it's not been updated since 1.7, but I guess the code might be salvageable...

**Comment by YoLaw** [comment]
May be! I think you can decompile this :)

**Comment by pgmann** [comment]
Decompiled version: https://pgmann.cf/projects/mc/RandomCoords.zip

**Comment by AmauryCarrade** [comment]
Look at the comments: [there's a source code here](https://github.com/BlackSpectrum/RandomCoords) (decompiled and refactored for an older version).
