### ISSUE TITLE
Global chat

### ISSUE THREAD

**Issue by YoLaw** [pgmann/SpectatorPlus#70]
Hello (It's me again! ) 
In your plugin, we have a spec chat. It is very good! But there isn't any solution to talk in global chat...
For example, we could chat in global with a special caracter like "!" or "@"! :)
Thanks and have a nice day! :)

**Comment by pgmann** [comment]
Yeah, it's designed to prevent spectators warning users still in the game, e.g. "Look out <player> is sneaking up on you!"; "<player> has full diamond armour!".

**Comment by YoLaw** [comment]
With a permission, it could be useful for example for admins! :)

**Comment by pgmann** [comment]
They can use `/broadcast` or `/say` instead.

**Comment by YoLaw** [comment]
Yes I'm using that for moment ^^

**Comment by pgmann** [comment]
What do you think about this, @AmauryCarrade? Is it worth adding?
It is quite easy to add after all, just a permission node and an exclusion on the chat filter...

**Comment by AmauryCarrade** [comment]
I think it's a good idea, especially for administrators.

And yes, it's [pretty easy to implement](https://github.com/zDevelopers/UHPlugin/blob/dev/src/main/java/eu/carrade/amaury/UHCReloaded/teams/TeamChatManager.java#L173-L186)...

**Comment by pgmann** [comment]
Okay, shall we say `!` should be the 'escape symbol'?

**Comment by AmauryCarrade** [comment]
You can make it configurable. Or add a command to send a global message. Or both. I suggest both.
